modules/admin/controllers/AnswerController.php
<?php

namespace app\modules\admin\controllers;

use Yii;
use app\models\Answer;
use app\models\AnswerSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * AnswerController implements the CRUD actions for Answer model.
 */
class AnswerController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Answer models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new AnswerSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        if(Yii::$app->getRequest()->isAjax){
            return $this->renderAjax('index', [
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider,
            ]);
        }else{
            return $this->render('index', [
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider,
            ]);
        }
    }

    /**
     * Displays a single Answer model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Answer model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Answer();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->answers_id]);
        }

        return $this->render('create', [
            'model' => $model,
            'quiz' => app\models\Quiz::find()->where([])->one()
        ]);
    }

    /**
     * Updates an existing Answer model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->answers_id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Answer model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();
        return ;

        return $this->redirect(['index']);
    }

    /**
     * Finds the Answer model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Answer the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Answer::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

modules/admin/controllers/QuestionsController.php
<?php

namespace app\modules\admin\controllers;

use Yii;
use app\models\Questions;
use app\models\QuestionsSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\Answer;

/**
 * QuestionsController implements the CRUD actions for Questions model.
 */
class QuestionsController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Questions models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new QuestionsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Questions model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Questions model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($quiz,$id=false)
    {
        if(!$id)
            $model = new Questions();
        else
            $model = Questions::findOne($id);    
        $model->created_at = new \yii\db\Expression('NOW()');
        $model->updated_at = new \yii\db\Expression('NOW()');
        
        if ($model->load(Yii::$app->request->post()) && $model->save()) {

            if(count(Yii::$app->request->post('Answer')['answer']) > 0){
                foreach(Yii::$app->request->post('Answer')['answer'] as $l => $reg){
                    $respostas = new Answer();
                    if(Yii::$app->request->post('Answer')['answers_id'][$l]){
                        $respostas = Answer::findOne(Yii::$app->request->post('Answer')['answers_id'][$l]);
                        $respostas->updated_at = new \yii\db\Expression('NOW()');  
                    }else{
                        $respostas->created_at = new \yii\db\Expression('NOW()');
                        $respostas->updated_at = new \yii\db\Expression('NOW()');  
                        $respostas->question_id = $model->quest_id;
                    }

                    $respostas->answer = $reg;

                    if(Yii::$app->request->post('Answer')['is_correct'][$l])
                        $respostas->is_correct = 1;
                    else
                        $respostas->is_correct = 0;
                    
                    $respostas->save();
                }
            }
            return $this->redirect(['quiz/view', 'id' => $model->quiz_id]);
        }

        if(Yii::$app->getRequest()->isAjax){
            return $this->renderAjax('create', [
                'model' => $model,
                'quiz' => $quiz
            ]);
        }else{
            return $this->render('create', [
                'model' => $model,
                'quiz' => $quiz
            ]);
        }
    }

    /**
     * Updates an existing Questions model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['quiz/view', 'id' => $model->quiz_id]);
        }

        if(Yii::$app->getRequest()->isAjax){
            return $this->renderAjax('create', [
                'model' => $model,
                'quiz' => $model->quiz_id
            ]);
        }else{
            return $this->render('create', [
                'model' => $model,
                'quiz' => $model->quiz_id
            ]);
        }
    }

    /**
     * Deletes an existing Questions model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDeletar($id)
    {
        $model = $this->findModel($id);
        $id = $model->quiz_id;
        $model->delete();

        return $this->redirect(['quiz/view', 'id' => $id]);
    }

    /**
     * Finds the Questions model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Questions the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Questions::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

modules/admin/views/questions/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use app\models\Answer;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model app\models\Questions */
/* @var $form yii\widgets\ActiveForm */

$js = 'var form1 = "";';

if($model->quest_id){
    $m = Answer::findAll(['question_id' => $model->quest_id]);
    $i = 1;
    foreach($m as $row){
        if($i == 1){
            $js .= '
            $(".tabela").show().removeClass("hide");
            ';
        }
        $js .= '
        form1 += "<table id=\'remove'.$i.'\' width=\'100%\' style=\'margin-bottom:10px\' class=\'tabela\'><tr><td style=\'width:10%\'><a href=\'javascript:void(0)\' class=\'remove\' data-value=\'remove'.$i.'\' data-reg=\''.$row->answers_id.'\'>Remover</a></td><td style=\'width:70%; padding-right: 10px\'><input type=\'text\' class=\'form-control\' name=\'Answer[answer]['.$i.']\' value=\''.$row->answer.'\' maxlength=\'255\' aria-invalid=\'false\'></td><td> <input type=\'hidden\' name=\'Answer[answers_id]['.$i.']\' value=\''.$row->answers_id.'\' /><input type=\'hidden\' name=\'Answer[is_correct]['.$i.']\' value=\'0\' /><input type=\'checkbox\' name=\'Answer[is_correct]['.$i.']\' value=\'1\' '.($row->is_correct? 'checked':'').' /></td></tr></table>";
        ';
        $i++;
    }
    
    $js .= '
    $(".opcoes").append(form1);
    $(".remove").on("click",function(){
        var op = $(this);
        var r = confirm("Deseja remover essa opção?");
        if (r == true) {
            $.post("'.Url::to(['answer/delete']).'?id="+$(this).attr("data-reg"),function(){
                RmOpcao(op);
            });
        }         
    });
    ';
}

$js .= '
    var add = function(){
        var i = $(".tabela").length;
        var form = "<table id=\'remove"+i+"\' width=\'100%\' style=\'margin-bottom:10px\' class=\'tabela\'><tr><td style=\'width:10%\'><a href=\'javascript:void(0)\' class=\'remove\' data-value=\'remove"+i+"\' data-reg=\'0\'>Remover</a></td><td style=\'width:70%; padding-right: 10px\'><input type=\'text\' class=\'form-control\' name=\'Answer[answer]["+i+"]\' value=\'\' maxlength=\'255\' aria-invalid=\'false\'></td><td> <input type=\'hidden\' name=\'Answer[answers_id]["+i+"]\' value=\'0\' /><input type=\'hidden\' name=\'Answer[is_correct]["+i+"]\' value=\'0\' /><input type=\'checkbox\' name=\'Answer[is_correct]["+i+"]\' value=\'1\' /></td></tr></table>";

        $(".tabela").show().removeClass("hide");
        
        $(".opcoes").append(form);
        $(".remove").on("click",function(){
            RmOpcao($(this));
        });
    };

    $(".adicionar").on("click",add);

    function RmOpcao(op){
        var id = op.attr("data-value");
        $("#"+id).remove();
        if($(".tabela").length <= 1){
            $(".tabela").addClass("hide");
        }
    }    
';


$this->registerJs($js);
?>

<div class="questions-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'quiz_id')->hiddenInput(['value' => $quiz])->label(false) ?>

    <?= $form->field($model, 'subject')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'type')->checkbox() ?>

    <hr />
    <h2>Opções</h2>
    <div class="form-group">
        <?= Html::button('Adicionar +', ['class' => 'btn btn-primary adicionar']) ?>
    </div>

    <div class="form-group opcoes">
        <table width='100%' class="tabela hide">
            <tr>
                <td style='width: 10%'>Ação</td>
                <td style='width: 70%'>Resposta</td>
                <td style='width: 20%'>Resp. Correta</td>
            </tr>

        </table>    
    </div>

    <div class="form-group text-right">
        <?php
        if($model->quest_id){
            echo Html::a('Deletar', ['deletar', 'id' => $model->quest_id], [
                'class' => 'btn btn-danger',
                'data' => [
                    'confirm' => 'Deseja remover essa questão?',
                    'method' => 'post',
                ],
            ]);
        }
        ?>
        <?= Html::submitButton('Salvar', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/admin/views/questions/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\QuestionsSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="questions-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>

    <?= $form->field($model, 'quest_id') ?>

    <?= $form->field($model, 'quiz_id') ?>

    <?= $form->field($model, 'subject') ?>

    <?= $form->field($model, 'type') ?>

    <?= $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/admin/views/questions/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Questions */

$this->title = 'Cadastrar Questão';
$this->params['breadcrumbs'][] = ['label' => 'Questões', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="questions-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'quiz' => $quiz
    ]) ?>

</div>

modules/admin/views/questions/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
use yii\helpers\Url;
use prawee\widgets\ButtonAjax;
use app\models\Answer;
/* @var $this yii\web\View */
/* @var $searchModel app\models\QuestionsSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Questões';

$this->registerJs('
function AbrirModal(url){
    $("#main-modal").modal("show")
    .find("#main-content-modal")
    .load(url);
}

$("#main-modal").on("hidden.bs.modal", function () {
    $("#main-modal .modal-body").html("<div id=\'main-content-modal\'><p class=\'text-center\'>Carregando...</p></div>");
});

$(".DeleteQuest").on("click",function(e){
    var r = confirm("Deseja remover essa questão?");
    if (r == false) {
        e.preventDefault();
    }
});

');
?>
<div class="questions-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php Pjax::begin(); ?>

    <p>
        <?= ButtonAjax::widget([
        'name'=>'Adicionar',
        'route'=>['questions/create','quiz' => $quiz],
        'modalId'=>'#main-modal',
        'modalContent'=>'#main-content-modal',
        'options'=>[
            'class'=>'btn btn-success',
            'title'=>'Button for create application',
        ]
    ]); ?>

    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            'subject:ntext',
            [
                'attribute' => 'type',
                'value' => function($model){
                    return $model->type? 'Sim' : 'Não';
                }
            ],
            [
                'label' => 'Acertos',
                'value' => function($model){

                    $quest = app\models\QuizUser::find()->where(['quest_id' => $model->quest_id])->all();
                    $ids = array();
                    foreach($quest as $row){
                        $ids[] = $row->quiz_user_id;
                    }

                    return app\models\AnswersUser::find()->where(['quiz_user_id' => $ids, 'acerto' => 1])->count();
                }
            ],
            [
                'attribute' => 'created_at',
                'value' => function($model){
                    return Yii::$app->formatter->asDateTime($model->created_at);
                }
            ],
            [
                'attribute' => 'updated_at',
                'value' => function($model){
                    return Yii::$app->formatter->asDateTime($model->updated_at);
                }
            ],

            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{update} {delete}',
                'buttons' => [
                    'update' => function ($url,$model) {
                        $this->registerJs('
                        $("span.glyphicon.glyphicon-pencil").click(function(e){
                            e.preventDefault();
                            AbrirModal("'.Url::to(['questions/create','id' => $model->quest_id]).'&quiz='.$model->quiz_id.'");
                        });
                        '
                        );

                        return Html::a(
                            '<span class="glyphicon glyphicon-pencil"></span>', 
                            Url::to(['questions/create','id' => $model->quest_id])."&quiz=".$model->quiz_id);
                    },
                    'delete' => function ($url,$model) {
                        return Html::a(
                            '<span class="glyphicon glyphicon-trash DeleteQuest"></span>',
                            Url::to(['questions/deletar','id' => $model->quest_id])
                            );
                    }
                ]
            ],
        ],
    ]); ?>
    <?php Pjax::end(); ?>
</div>

modules/admin/views/questions/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Questions */

$this->title = 'Editar questão';
$this->params['breadcrumbs'][] = ['label' => 'Questões', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->quest_id, 'url' => ['view', 'id' => $model->quest_id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="questions-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'quiz' => $quiz
    ]) ?>

</div>

modules/admin/views/questions/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Questions */

$this->title = $model->quest_id;
$this->params['breadcrumbs'][] = ['label' => 'Questões', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="questions-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->quest_id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->quest_id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'quest_id',
            'quiz_id',
            'subject:ntext',
            'type',
            'created_at',
            'updated_at',
        ],
    ]) ?>

</div>